name: amd64_linux_gcc

on: 
  push:
    paths:
        - '.github/workflows/amd64_linux_gcc.yml'
jobs:

  amd64_linux_gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt -y -qq update
    - run: sudo apt install -y g++ cmake qt5-default libqt5webkit5-dev python
      name: Install requirements
    - run: g++ --version && cmake --version && qmake --version && python --version
      name: Display tools version
    - run: ./configure --disable-debug --pass-thru -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_FIND_LIBRARY_SUFFIXES=.a
    - run: make
    - run: file ./bin/phantomjs
    - run: ./bin/phantomjs --version
    - run: make check
    - run: cd ./bin && tree .

    - name: Release1
      uses: softprops/action-gh-release@v2
      with:
        tag_name: 'phantomjs_amd64_linux_gcc'
        name: 'phantomjs.zip'
        files: |
          ./bin/*